config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  resources :newsletters, only: [:create, :destroy], params: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newsletter.rb
# frozen_string_literal: true

class Newsletter < ApplicationRecord
  # Validations
  validates :email, presence: true, uniqueness: true
  validates :token, uniqueness: true, allow_blank: true  

  # Methods
  def signup!
    self.token = SecureRandom.hex(10)
    self.active = true
    save!
  end

  def cancel!
    self.token = nil
    self.active = false
    save!
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @newsletter = Newsletter.new
  end
end

app/controllers/newsletters_controller.rb
# frozen_string_literal: true

class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:destroy]

  def create
    newsletter = Newsletter.find_or_initialize_by(email: newsletter_params[:email])

    if newsletter.save && newsletter.signup!
      flash[:notice] = 'Você se inscreveu com sucesso.'
    else
      flash[:error] = 'Falha ao se inscrever, tente novamente.'
    end

    redirect_to root_path
  end

  def destroy
    if @newsletter.cancel!
      flash[:success] = 'Newsletter cancelada com sucesso'
    else
      flash[:error] = 'Falha ao cancelar a newsletter'
    end

    redirect_to root_path
  end

  private

  def newsletter_params
    params.require(:newsletter).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% provide :title, 'Senior Shopping Brasil' %>

<section id="hero" class="py-5">
  <div class="container py-5">
    <div class="row py-5">
      <div class="col-md-6 offset-md-3 text-center">
        <%= image_tag('logo.jpeg', class: 'brand-logo') %>
        <h2 class="fw-bold text-center mb-2">Estamos chegando</h2>
        <h5 class="fw-bold mt-2 mb-3">Lançamento 01/09</h5>
        <p class='mb-4'>Nosso site entra no ar em 
        <span class="fw-bold">1º de setembro</span>.<br> 
        Seja o <span class="fw-bold">primeiro a saber.</span></p>

        <div class="row">
          <div class="col-md-10 offset-md-1">
            <div class="card">
              <div class="card-body">
                <%= render partial: 'newsletters/form',
                  locals: { newsletter: @newsletter }
                %>
              </div>
            </div>            
          </div>
        </div>

        <ul class="list-unstyled list-inline mt-5 gap-3 social-links">
          <li class="list-inline-item">
            <%= link_to '#' do %>
              <i class="fa-brands fa-facebook"></i>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to 'http://instagram.com/seniorshopping_brasil' do %>
              <i class="fa-brands fa-instagram"></i>
            <% end %>
          </li>
          <li class="list-inline-item">
            <%= link_to 'mailto:contato@seniorshop.com.br' do %>
              <i class="fa-solid fa-envelope"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title><%= content_for(:title) || "Senior Shopping App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/5165849ba2.js" crossorigin="anonymous"></script>
  </head>
  <body class="<%= controller.controller_name %>">
    <%= yield %>
  </body>
</html>

app/views/newsletters/_form.html.erb
<%= form_for(:newsletter, url: newsletters_path, method: :post, html: { class: "newsletter-form" }) do |f| %>
  <div class="input-group input-group-lg pt-2">
    <%= f.email_field :email,
      class: "form-control",
      required: true,
      placeholder: "Seu melhor e-mail",
      autocomplete: "email",
      'aria-label': "E-mail para avisos" %>

    <button type="submit" class="btn btn-primary">
      Quero ser avisado(a)
    </button>
  </div>

  <div class="form-text mt-3">Sem spam. Você pode sair 
    <span class="fw-bold">quando quiser.</span>
  </div>
<% end %>